name = "umami-proxy"
main = "worker-simple.js"
compatibility_date = "2024-01-01"

# 环境变量配置
[vars]
# Umami 实例地址
UMAMI_URL = "https://stats.upxuu.com"
# Umami API Token（通过 /api/auth/login 获取）
UMAMI_TOKEN = "bUeO7XXbCJbFXnZ5FPOYPghzkB0hYQqmRKDxHBJmdu/yoNMde4rvkfuhK4A3h0hUkt/ovKSK9xG3"
# 网站 ID
UMAMI_WEBSITE_ID = "cd983d6c-e011-489d-903f-4757ce41c14d"
